apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybriddeployable-operator
  labels:
    app.kubernetes.io/instance: hybriddeployable-operator
    app.kubernetes.io/managed-by: hybriddeployable-operator
    app.kubernetes.io/name: hybridApplication
